name: Demo CICD APP

on:
    pull_request:
        branches: 
             -main

jobs:
    test:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./src/

        strategy:
            matrix:
                node-version: [12, 14, 16]
                os: [ubuntu-latest, macos-latest, windows-latest]

        env:
            MODE: 'dev'

        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version}}

            - name: Install dependencies
              run: npm install
            # or npm ci we can use | to add more commands
            - name: Run Test
              run: npm test

            - name: Build
              run: npm run build
